#USING THE (TRY,EXCEPT) TO HANDLE EXCEPTIONS IN PYTHON  
num = [1,2,3,4]
for i in num:
    try: 
        div = (i / 0)
        print (div)
        
    raise Exception

        





    

       
  